name: Android CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Initialize Gradle Wrapper
      # 重点：进入第二层 easycontrol 文件夹，因为那里才有 settings.gradle
      run: gradle wrapper
      working-directory: easycontrol

    - name: Grant execute permission for gradlew
      run: chmod +x easycontrol/gradlew

    - name: Build with Gradle
      # 重点：在正确的目录下运行编译命令
      run: ./gradlew assembleDebug --stacktrace
      working-directory: easycontrol

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Easycontrol-Fixed-APK
        # 递归搜索所有生成的 apk
        path: "**/build/outputs/apk/debug/*.apk"
