name: Android CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Initialize Gradle Wrapper
      # 重点：进入 easycontrol 文件夹生成 wrapper
      run: gradle wrapper
      working-directory: .

    - name: Build with Gradle
      # 重点：这里执行编译命令，并指向具体的文件夹
      run: ./gradlew assembleDebug --stacktrace
      # 如果你的 gradlew 在根目录生成了，就直接跑；
      # 如果编译还提示找不到 build.gradle，请把下面这行取消注释：
      # working-directory: . 

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Easycontrol-APK
        path: "**/build/outputs/apk/debug/*.apk"
